### ISSUE TITLE
关于 extract value 

### ISSUE THREAD

**Issue by chaozhang111** [kbxu/brant#2]
徐老师您好：
utility 里面的 extract value  这一功能：说明中写的是ROI file used for extracting _mean intensity_ in each roi tagged by number,请问 这个 “mean intensity”具体指的是什么？图像的密度？信号强度？体积？其他。。。？ 谢谢

**Comment by kbxu** [comment]
@chaozhang111 你好，这里指的是均值，intensity就是图像里显示的强度，就是体素的值。

**Comment by chaozhang111** [comment]
谢谢，徐老师！

**Comment by chaozhang111** [comment]
谢谢，徐老师！BRANT 真是不错的软件，最近在使用，有问题还要多多请教！
张 超
徐州医科大学附属医院影像科

在 2019-01-02 08:58:25，"kbxu" <notifications@github.com> 写道：


@chaozhang111 你好，这里指的是均值，intensity就是图像里显示的强度，就是体素的值。

**Comment by kbxu** [comment]
不客气，有问题请随时反馈！
